{
 "title": "TestDashBoard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Disk Space Used",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"node-exporter_host:9100\",device!~'rootfs'}-node_filesystem_avail_bytes{instance=\"node-exporter_host:9100\",device!~'rootfs'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_filesystem_avail_bytes{instance=\"node-exporter_host:9100\", device!~\"'rootfs'\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "RAM Avalable",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"node-exporter_host:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_load1{instance=\"node-exporter_host:9100\"}",
     "legendFormat": "cpu load1"
    },
    {
     "expr": "node_load5{instance=\"node-exporter_host:9100\"}",
     "legendFormat": "cpu load5"
    },
    {
     "expr": "node_load15{instance=\"node-exporter_host:9100\"}",
     "legendFormat": "cpu load15"
    }
   ]
  },
  {
   "title": "CPU IDLE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 - sum by (mode)(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"node-exporter_host:9100\", job=\"node_host\"}[$__rate_interval])) * 100"
    }
   ]
  }
 ]
}