[sources.our_log]
type = "file"
ignore_older_secs = 600
include = [ "/home/centos/logs/*.log" ]
read_from = "beginning"
[sinks.to_clickhouse]
type = "clickhouse"
inputs = [ "our_log" ]
database = "custom"
endpoint = "http://51.250.90.221:8123"
table = "my_table"
compression = "gzip"