---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: "51.250.15.134"
      ansible_user: centos
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
vector:
  hosts:
    vector-01:
      ansible_host: "51.250.15.48" 
      ansible_user: centos
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: "51.250.13.131"
      ansible_user: centos
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
