---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 51.250.65.206
      ansible_user: centos
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
vector:
  hosts:
    vector-01:
      ansible_host: 51.250.92.136
      ansible_user: centos
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
